language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - cmake
      - cmake-data
env:
  - LLVM_VERSION=3.8.0
  - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang-$LLVM_VERSION
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
  - cd clang-$LLVM_VERSION
  - sudo cp -R * /usr/local/
script:
  - ( mkdir build_gcc4 && cd build_gcc4 && cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCINDER_REAL_WIDTH=4 && make && make test ARGS=-V )
  - ( mkdir build_gcc8 && cd build_gcc8 && cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCINDER_REAL_WIDTH=8 && make && make test ARGS=-V )
  - ( mkdir build_gcc10 && cd build_gcc10 && cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCINDER_REAL_WIDTH=10 && make && make test ARGS=-V )
  - ( mkdir build_clang4 && cd build_clang4 && cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCINDER_REAL_WIDTH=4 && make && make test ARGS=-V )
  - ( mkdir build_clang8 && cd build_clang8 && cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCINDER_REAL_WIDTH=8 && make && make test ARGS=-V )
  - ( mkdir build_clang10 && cd build_clang10 && cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCINDER_REAL_WIDTH=10 && make && make test ARGS=-V )

